# Generated by Django 3.1 on 2020-08-14 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='quenstion',
            new_name='question',
        ),
    ]
